//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM.Integrations.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALM.Integrations.Common.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch&gt;
        ///  &lt;entity name=&quot;pcx_workpackage&quot;&gt;
        ///    &lt;attribute name=&quot;pcx_workpackageid&quot; /&gt;
        ///    &lt;attribute name=&quot;pcx_name&quot; /&gt;
        ///    &lt;attribute name=&quot;pcx_summary&quot; /&gt;
        ///    &lt;link-entity name=&quot;alm_workset&quot; from=&quot;alm_worksetid&quot; to=&quot;alm_worksetid&quot; alias=&quot;workset&quot;&gt;
        ///      &lt;attribute name=&quot;alm_worksetname&quot; /&gt;
        ///    &lt;/link-entity&gt;
        ///    &lt;link-entity name=&quot;alm_fercbusinessunit&quot; from=&quot;alm_fercbusinessunitid&quot; to=&quot;alm_fercbusinessunitid&quot; alias=&quot;bizunit&quot;&gt;
        ///      &lt;attribute name=&quot;alm_atmsfercorganizationcdfk&quot; /&gt;
        ///      &lt;attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewWorkItem {
            get {
                return ResourceManager.GetString("NewWorkItem", resourceCulture);
            }
        }
    }
}
